### ISSUE TITLE
soterd shouldn't sync with other soterd from different genesis. 

### ISSUE THREAD

**Issue by totaloutput** [soteria-dag/soterd#2]
when there are 2 nodes, one from an older genesis, the other one is from a newer genesis (this is common in early development, as we might regenerate genesis block multiple times a day) the problem is, the older node has higher `height`, so the newer node will try to sync with it, but the sync will never finish because it’s from different genesis, this prevents the new node accepting new blocks because it’s still in sync mode..

**Comment by colakong** [comment]
Issuing a `getblocks` or `getheaders` messages won't work for this, because the `inv` or `headers` response will be empty; we won't know that the empty response was related to the request for the genesis block.

We could update the `version` message to include the genesis block hash of the node, so that during the peer handshake a peer would have the opportunity to disconnect due to mis-matched genesis block.

**Comment by colakong** [comment]
I went with the `version` message update route, since info in that message is already used to determine if we should connect to a peer.
