### ISSUE TITLE
soterdash display dash shifting to right as the graph (dag) scrolls down.

### ISSUE THREAD

**Issue by totaloutput** [soteria-dag/soterd#7]
**Describe the bug**
in soterdash, the dag display page will shift to right when you scroll down.

**To Reproduce**
1. Go to https://www.soteriadag.org/
2. Click on status
3. click on DAG (if you are on mobile, click the menu then DAG)
4. scroll down.

**Expected behavior**
DAG displays and continue.

**Screenshots**
![image](https://user-images.githubusercontent.com/43481958/57799136-3936a300-7703-11e9-8cf7-423d1feb2d51.png)

![image](https://user-images.githubusercontent.com/43481958/57799150-3f2c8400-7703-11e9-8a40-0127079dd3c2.png)

![image](https://user-images.githubusercontent.com/43481958/57799167-45bafb80-7703-11e9-9b7a-3d9a8a8e53b0.png)

**this reproduce both on desktop and mobile. **

**Comment by colakong** [comment]
@totaloutput this _slide-to-the-right_ behaviour appears to come from graphviz. You can reproduce it with a dot file that doesn't contain any layout info.

[Here's a graphviz .dot file of the current testnet dag](https://f000.backblazeb2.com/file/duck-pond-reiki/dag.dot). If you render it to svg with:
```
cat dag.dot | dot -Tsvg > dag.svg
```

You'll see the same _slide-to-the-right_.

I think we should look into whether graphviz dot file format supports layout rules, so that we can keep the history of dag fairly straight even when it's quite long.

**Comment by colakong** [comment]
Using the graph-level `ordering=out` attribute seems to help keep a tighter left-aligned graph for large dag renderings. In testing it didn't render beyond the boundaries of the screen.

I have a patch committed that applies this. We'll use it for now, and explore subgraphs or invisible edges as other means of maintaining layout if the need arises.

I'll push the patch along with the fix for #8.

**Comment by colakong** [comment]
A fix for this was included in `soterd` commit [2625c407](https://github.com/soteria-dag/soterd/commit/2625c407441979b8d7c0045db75aff1e58cb96f6#diff-3ec96b3a64240caa11322b030a17f398) and `soterdash` commit [eb5208d](https://github.com/soteria-dag/soterdash/commit/eb5208d3c42f94c6c0f2fa5bed22e55d56121c7b#diff-3e581d8dfce7796ee8aff0a5df32b261)
